### PR TITLE
add stuff

### PR DESCRIPTION
**Pull request by Rahib777-7**

### CODE REVIEW

**Comment by Rahib777-7** [comment]
some stuff that this does is prevent dmca

**Comment by TheUnblockedHubOfficial** [comment]
Can you test this in a deployment to something like herkou to make sure it doesn’t break the site

**Comment by Rahib777-7** [comment]
> Can you test this in a deployment to something like herkou to make sure it doesn’t break the site

it wont

**Comment by TheUnblockedHubOfficial** [comment]
It won't work some dependencies require a newer version of node/npm

**Comment by Rahib777-7** [comment]
> It won't work some dependencies require a newer version of node/npm

ill revert those changes then

**Pull request closed without merging**
